name: Regression Tests

on:
  push:
    branches:
      - master
      - 'feature/**'
  workflow_dispatch:

jobs:
  regression:
    strategy:
      matrix:
        include:
          - platform: aws
            language: python
            version: "3.11"
          - platform: aws
            language: nodejs
            version: "16"
      fail-fast: false

    uses: ./.github/workflows/_regression-job.yml
    with:
      platform: ${{ matrix.platform }}
      language: ${{ matrix.language }}
      version: ${{ matrix.version }}
    secrets: inherit
